$env:WATCOM = "C:\WATCOM"
$env:EDPATH = "C:\WATCOM\EDDAT"
$env:WHTMLHELP = "C:\WATCOM\BINNT\HELP"
$env:WIPFC = "C:\WATCOM\WIPFC"
$env:LIBPATH = "C:\WATCOM\lib386\"

$env:INCLUDE += ";C:\WATCOM\H;C:\WATCOM\H\NT;C:\WATCOM\H\NT\DIRECTX;C:\WATCOM\H\NT\DDK"
$env:Path += ";C:\WATCOM\BINNT64;C:\WATCOM\BINNT"
