name: ci

on:
  push:
    paths:
      - "**.cpp"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "**.cpp"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"

jobs:

  windows-msvc:
    timeout-minutes: 5
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -Bbuild -G "Visual Studio 17 2022"

    - name: Build
      run: cmake --build build --config Release --parallel

  windows-gcc:
    timeout-minutes: 5
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -Bbuild -G "MinGW Makefiles"

    - name: Build
      run: cmake --build build --parallel

  linux:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cxx: [g++, clang++]

    steps:
    - uses: actions/checkout@v2

    - name: install prereqs
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libxi-dev libx11-dev libpulse-dev

    - name: Configure
      run: cmake -Bbuild
      env:
        CXX: ${{ matrix.cxx }}

    - name: Build
      run: cmake --build build --parallel

  mac:
    timeout-minutes: 10
    runs-on: macos-latest

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
    - uses: actions/checkout@v2

    - name: install prereqs
      run: brew install libxi libx11 pulseaudio

    - name: Configure
      run: cmake -Bbuild

    - name: Build
      run: cmake --build build --parallel

  dos:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: open-watcom/setup-watcom@v0
      with:
        version: "2.0"

    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -Bbuild --toolchain dos.cmake

    - name: Build
      run: cmake --build build
